2025-09-12T19:49:19 {"block_run_id": 33, "block_uuid": "ingest_qb_invoice", "pipeline_run_id": 13, "pipeline_schedule_id": 1, "pipeline_uuid": "qb_invoices_backfill", "hostname": "963a983ada4e", "block_type": "data_loader", "level": "INFO", "message": "Start executing block with BlockExecutor.", "timestamp": 1757706559.010053, "uuid": "dd44bb79e0d7488bacbae3491af82e24"}
2025-09-12T19:49:20 {"block_run_id": 33, "block_uuid": "ingest_qb_invoice", "pipeline_run_id": 13, "pipeline_schedule_id": 1, "pipeline_uuid": "qb_invoices_backfill", "hostname": "963a983ada4e", "block_type": "data_loader", "level": "INFO", "message": "Nuevo access_token obtenido v\u00eda refresh_token", "timestamp": 1757706560.587549, "uuid": "fe39b78a4a7843d6bbbb80854450e1ec"}
2025-09-12T19:49:20 {"block_run_id": 33, "block_uuid": "ingest_qb_invoice", "pipeline_run_id": 13, "pipeline_schedule_id": 1, "pipeline_uuid": "qb_invoices_backfill", "hostname": "963a983ada4e", "block_type": "data_loader", "level": "INFO", "message": "Chunk 1: 2025-07-01T00:00:00Z \u2192 2025-07-07T23:59:59Z", "timestamp": 1757706560.605862, "uuid": "ba4bc39cb82b4a6199398eef28f6485c"}
2025-09-12T19:49:20 {"block_run_id": 33, "block_uuid": "ingest_qb_invoice", "pipeline_run_id": 13, "pipeline_schedule_id": 1, "pipeline_uuid": "qb_invoices_backfill", "hostname": "963a983ada4e", "block_type": "data_loader", "level": "INFO", "message": "Request API: 2025-07-01T00:00:00Z \u2192 2025-07-07T23:59:59Z, posici\u00f3n=1, intento 1", "timestamp": 1757706560.606354, "uuid": "199fafa06cb14167bfd433a131b9cc64"}
2025-09-12T19:49:22 {"block_run_id": 33, "block_uuid": "ingest_qb_invoice", "pipeline_run_id": 13, "pipeline_schedule_id": 1, "pipeline_uuid": "qb_invoices_backfill", "hostname": "963a983ada4e", "block_type": "data_loader", "level": "INFO", "message": "Posici\u00f3n 1 \u2192 0 invoices", "timestamp": 1757706562.09246, "uuid": "6ed07a38a46442ce9c55e6308e5dc76a"}
2025-09-12T19:49:22 {"block_run_id": 33, "block_uuid": "ingest_qb_invoice", "pipeline_run_id": 13, "pipeline_schedule_id": 1, "pipeline_uuid": "qb_invoices_backfill", "hostname": "963a983ada4e", "block_type": "data_loader", "level": "INFO", "message": "Chunk 1 devolvi\u00f3 0 invoices", "timestamp": 1757706562.104717, "uuid": "bf10e77075cb4a03b19fca8653ef8e90"}
2025-09-12T19:49:22 {"block_run_id": 33, "block_uuid": "ingest_qb_invoice", "pipeline_run_id": 13, "pipeline_schedule_id": 1, "pipeline_uuid": "qb_invoices_backfill", "hostname": "963a983ada4e", "block_type": "data_loader", "level": "INFO", "message": "Chunk 2: 2025-07-08T00:00:00Z \u2192 2025-07-14T23:59:59Z", "timestamp": 1757706562.110428, "uuid": "396f10b45fb14658814b7c18cf612ba0"}
2025-09-12T19:49:22 {"block_run_id": 33, "block_uuid": "ingest_qb_invoice", "pipeline_run_id": 13, "pipeline_schedule_id": 1, "pipeline_uuid": "qb_invoices_backfill", "hostname": "963a983ada4e", "block_type": "data_loader", "level": "INFO", "message": "Request API: 2025-07-08T00:00:00Z \u2192 2025-07-14T23:59:59Z, posici\u00f3n=1, intento 1", "timestamp": 1757706562.115023, "uuid": "04b1356679ea4f68b10db30a9df06278"}
2025-09-12T19:49:23 {"block_run_id": 33, "block_uuid": "ingest_qb_invoice", "pipeline_run_id": 13, "pipeline_schedule_id": 1, "pipeline_uuid": "qb_invoices_backfill", "hostname": "963a983ada4e", "block_type": "data_loader", "level": "INFO", "message": "Posici\u00f3n 1 \u2192 0 invoices", "timestamp": 1757706563.148292, "uuid": "4983e46759f74212915dd21d1258a21b"}
2025-09-12T19:49:23 {"block_run_id": 33, "block_uuid": "ingest_qb_invoice", "pipeline_run_id": 13, "pipeline_schedule_id": 1, "pipeline_uuid": "qb_invoices_backfill", "hostname": "963a983ada4e", "block_type": "data_loader", "level": "INFO", "message": "Chunk 2 devolvi\u00f3 0 invoices", "timestamp": 1757706563.15628, "uuid": "859efde9bfda43fbacd75d971ff2a4dc"}
2025-09-12T19:49:23 {"block_run_id": 33, "block_uuid": "ingest_qb_invoice", "pipeline_run_id": 13, "pipeline_schedule_id": 1, "pipeline_uuid": "qb_invoices_backfill", "hostname": "963a983ada4e", "block_type": "data_loader", "level": "INFO", "message": "Chunk 3: 2025-07-15T00:00:00Z \u2192 2025-07-21T23:59:59Z", "timestamp": 1757706563.157539, "uuid": "082c3c4f50f24343ae488719d33c0519"}
2025-09-12T19:49:23 {"block_run_id": 33, "block_uuid": "ingest_qb_invoice", "pipeline_run_id": 13, "pipeline_schedule_id": 1, "pipeline_uuid": "qb_invoices_backfill", "hostname": "963a983ada4e", "block_type": "data_loader", "level": "INFO", "message": "Request API: 2025-07-15T00:00:00Z \u2192 2025-07-21T23:59:59Z, posici\u00f3n=1, intento 1", "timestamp": 1757706563.15849, "uuid": "47efe28ea35a4bc3931ba6dd75ce5251"}
2025-09-12T19:49:24 {"block_run_id": 33, "block_uuid": "ingest_qb_invoice", "pipeline_run_id": 13, "pipeline_schedule_id": 1, "pipeline_uuid": "qb_invoices_backfill", "hostname": "963a983ada4e", "block_type": "data_loader", "level": "INFO", "message": "Posici\u00f3n 1 \u2192 0 invoices", "timestamp": 1757706564.121375, "uuid": "8883e0a8845149bf81169078c823c781"}
2025-09-12T19:49:24 {"block_run_id": 33, "block_uuid": "ingest_qb_invoice", "pipeline_run_id": 13, "pipeline_schedule_id": 1, "pipeline_uuid": "qb_invoices_backfill", "hostname": "963a983ada4e", "block_type": "data_loader", "level": "INFO", "message": "Chunk 3 devolvi\u00f3 0 invoices", "timestamp": 1757706564.130655, "uuid": "5b99618763414098a3bf1334f21fedc1"}
2025-09-12T19:49:24 {"block_run_id": 33, "block_uuid": "ingest_qb_invoice", "pipeline_run_id": 13, "pipeline_schedule_id": 1, "pipeline_uuid": "qb_invoices_backfill", "hostname": "963a983ada4e", "block_type": "data_loader", "level": "INFO", "message": "Chunk 4: 2025-07-22T00:00:00Z \u2192 2025-07-28T23:59:59Z", "timestamp": 1757706564.131498, "uuid": "b9128208116b4759b24c6ad609274d7a"}
2025-09-12T19:49:24 {"block_run_id": 33, "block_uuid": "ingest_qb_invoice", "pipeline_run_id": 13, "pipeline_schedule_id": 1, "pipeline_uuid": "qb_invoices_backfill", "hostname": "963a983ada4e", "block_type": "data_loader", "level": "INFO", "message": "Request API: 2025-07-22T00:00:00Z \u2192 2025-07-28T23:59:59Z, posici\u00f3n=1, intento 1", "timestamp": 1757706564.13175, "uuid": "394f4ecd5040435fa86cd8adef8ee2e1"}
2025-09-12T19:49:25 {"block_run_id": 33, "block_uuid": "ingest_qb_invoice", "pipeline_run_id": 13, "pipeline_schedule_id": 1, "pipeline_uuid": "qb_invoices_backfill", "hostname": "963a983ada4e", "block_type": "data_loader", "level": "INFO", "message": "Posici\u00f3n 1 \u2192 0 invoices", "timestamp": 1757706565.097024, "uuid": "0d1b601b30fe4291947b7afea860fbdb"}
2025-09-12T19:49:25 {"block_run_id": 33, "block_uuid": "ingest_qb_invoice", "pipeline_run_id": 13, "pipeline_schedule_id": 1, "pipeline_uuid": "qb_invoices_backfill", "hostname": "963a983ada4e", "block_type": "data_loader", "level": "INFO", "message": "Chunk 4 devolvi\u00f3 0 invoices", "timestamp": 1757706565.100243, "uuid": "48c056f61abd446eb6b5c5e14852dfbc"}
2025-09-12T19:49:25 {"block_run_id": 33, "block_uuid": "ingest_qb_invoice", "pipeline_run_id": 13, "pipeline_schedule_id": 1, "pipeline_uuid": "qb_invoices_backfill", "hostname": "963a983ada4e", "block_type": "data_loader", "level": "INFO", "message": "Chunk 5: 2025-07-29T00:00:00Z \u2192 2025-08-04T23:59:59Z", "timestamp": 1757706565.101271, "uuid": "b11eee6692604679af8a40a2f21c19e0"}
2025-09-12T19:49:25 {"block_run_id": 33, "block_uuid": "ingest_qb_invoice", "pipeline_run_id": 13, "pipeline_schedule_id": 1, "pipeline_uuid": "qb_invoices_backfill", "hostname": "963a983ada4e", "block_type": "data_loader", "level": "INFO", "message": "Request API: 2025-07-29T00:00:00Z \u2192 2025-08-04T23:59:59Z, posici\u00f3n=1, intento 1", "timestamp": 1757706565.101677, "uuid": "2dcc84dd083746a881796249778b79de"}
2025-09-12T19:49:26 {"block_run_id": 33, "block_uuid": "ingest_qb_invoice", "pipeline_run_id": 13, "pipeline_schedule_id": 1, "pipeline_uuid": "qb_invoices_backfill", "hostname": "963a983ada4e", "block_type": "data_loader", "level": "INFO", "message": "Posici\u00f3n 1 \u2192 31 invoices", "timestamp": 1757706566.530379, "uuid": "8d409839653f41b1a7636ea3654f1949"}
2025-09-12T19:49:26 {"block_run_id": 33, "block_uuid": "ingest_qb_invoice", "pipeline_run_id": 13, "pipeline_schedule_id": 1, "pipeline_uuid": "qb_invoices_backfill", "hostname": "963a983ada4e", "block_type": "data_loader", "level": "WARNING", "message": "Exception thrown when attempting to run <function BlockExecutor.execute.<locals>.__execute_with_retry at 0xffff8d3b8040>, attempt 1 of 1", "timestamp": 1757706566.545063, "uuid": "63a6f31632214d83a42fd8cc56377ca1", "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1154, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1691, in execute_sync\n    return __execute()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1668, in __execute\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1570, in __execute\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1910, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2073, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2169, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 156, in load_data_from_api\nNameError: name 'page_number' is not defined\n", "error_stack": ["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1442, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1830, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1226, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 794, in invoke\n    return callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 809, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 108, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 60, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1791, in schedule_all\n    PipelineScheduler(r).start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 159, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 198, in start\n    self.schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 159, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 334, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 641, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 21, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 122, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 199, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 353, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 317, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1311, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 46, in retry_func\n    logger.warning(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 39, in warning\n    self.__send_message('warning', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack()\n"], "error_stacktrace": "name 'page_number' is not defined"}
2025-09-12T19:49:26 {"block_run_id": 33, "block_uuid": "ingest_qb_invoice", "pipeline_run_id": 13, "pipeline_schedule_id": 1, "pipeline_uuid": "qb_invoices_backfill", "hostname": "963a983ada4e", "block_type": "data_loader", "level": "EXCEPTION", "message": "Failed to execute block ingest_qb_invoice", "timestamp": 1757706566.568746, "uuid": "91be0a4b3fa34fcea8241557f9ae2acd", "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1154, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1691, in execute_sync\n    return __execute()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1668, in __execute\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1570, in __execute\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1910, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2073, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2169, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 156, in load_data_from_api\nNameError: name 'page_number' is not defined\n", "error_stack": ["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1442, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1830, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1226, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 794, in invoke\n    return callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 809, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 108, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 60, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1791, in schedule_all\n    PipelineScheduler(r).start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 159, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 198, in start\n    self.schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 159, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 334, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 641, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 21, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 122, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 199, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 353, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 317, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1311, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 649, in execute\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack()\n"], "error_stacktrace": "name 'page_number' is not defined"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 647, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 621, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1154, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1691, in execute_sync
    return __execute()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1668, in __execute
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1570, in __execute
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1910, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2073, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2169, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 156, in load_data_from_api
NameError: name 'page_number' is not defined
